# Lokálny listener
listener 1883 0.0.0.0
allow_anonymous true

# Websockets (pre MQTT Explorer)
listener 9001 0.0.0.0
protocol websockets

# Bridge na vzdialený broker cez Tailscale
connection bridge-to-remote
address 10.99.94.39:1883
# ↑ Zmeň na Tailscale IP vzdialeného zariadenia

# Ktoré témy forwardovať
topic # out 0
topic # in 0

# Alebo len konkrétne témy:
# topic test/ps418ph/# both 0

# Ak vzdialený broker vyžaduje autentifikáciu:
# remote_username student
# remote_password dgRk9cQ8sU4fCO

# Bridge nastavenia
try_private false
cleansession true
notifications false
start_type automatic