services:
  postgres:
    image: postgres:16
    container_name: postgres-local
    environment:
      POSTGRES_USER: matotvrdon
      POSTGRES_PASSWORD: matotvrdon
      POSTGRES_DB: matotvrdon
    ports:
      - "5555:5432"
    volumes:
      - application_pgdata:/var/lib/postgresql/data

  mosquitto:
    image: eclipse-mosquitto:2.0.18
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    restart: unless-stopped

  mqtt-explorer:
    image: smeagolworms4/mqtt-explorer
    container_name: mqtt-explorer
    ports:
      - "4000:4000"
    environment:
      - HTTP_PORT=4000
    restart: unless-stopped

volumes:
  application_pgdata:
  mosquitto_data:
  mosquitto_log:
