// <auto-generated />
using System;
using Application.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Application.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260127140051_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Application.Models.Sensor", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Name");

                    b.ToTable("Sensor");
                });

            modelBuilder.Entity("Application.Models.Sensors.AirQuality", b =>
                {
                    b.Property<DateTime>("Dt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("dt");

                    b.Property<string>("Units")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("units");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasJsonPropertyName("value");

                    b.HasKey("Dt");

                    b.ToTable("AirQuality");
                });

            modelBuilder.Entity("Application.Models.Sensors.AirQualityPercent", b =>
                {
                    b.Property<DateTime>("Dt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("dt");

                    b.Property<string>("Units")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("units");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasJsonPropertyName("value");

                    b.HasKey("Dt");

                    b.ToTable("AirQualityPercent");
                });

            modelBuilder.Entity("Application.Models.Sensors.Humidity", b =>
                {
                    b.Property<DateTime>("Dt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("dt");

                    b.Property<string>("Units")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("units");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasJsonPropertyName("value");

                    b.HasKey("Dt");

                    b.ToTable("Humidity");
                });

            modelBuilder.Entity("Application.Models.Sensors.Motion", b =>
                {
                    b.Property<DateTime>("Dt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("dt");

                    b.Property<string>("Units")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("units");

                    b.Property<bool>("Value")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("value");

                    b.HasKey("Dt");

                    b.ToTable("Motion");
                });

            modelBuilder.Entity("Application.Models.Sensors.Temperature", b =>
                {
                    b.Property<DateTime>("Dt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("dt");

                    b.Property<string>("Units")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("units");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasJsonPropertyName("value");

                    b.HasKey("Dt");

                    b.ToTable("Temperature");
                });

            modelBuilder.Entity("Application.Models.Sensors.Window", b =>
                {
                    b.Property<DateTime>("Dt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("dt");

                    b.Property<string>("Units")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("units");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("value");

                    b.HasKey("Dt");

                    b.ToTable("Window");
                });

            modelBuilder.Entity("Application.Models.Ventilation.VentilationEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<double?>("Co2Ppm")
                        .HasColumnType("double precision");

                    b.Property<string>("DeviceId")
                        .HasColumnType("text");

                    b.Property<DateTime>("Dt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<bool?>("WindowOpen")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("VentilationEvent");
                });
#pragma warning restore 612, 618
        }
    }
}
